services:
  postgres:
    image: postgres:17-alpine
    container_name: readinpeace-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: readinpeace
      POSTGRES_PASSWORD: readinpeace
      POSTGRES_DB: readinpeace
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
